/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc_pi.h"
#include <stdlib.h>
#include <stdio.h>

#define OK 0 // Success
#define ERROR 1 // An error occured (oonly one: ngatve number)
#define MSG_SIZE 64 // Size of iinput
#define EXIT -1 // Not a code, but user input

// Get input from user and parse it to a request type structure
request_t get_input(void)
{
    request_t request;
    char line[MSG_SIZE];
    int line_int;

    while (1)
    {
        printf("Give a positive number or -1 to exit: ");
        fgets(line, MSG_SIZE, stdin);
        
        // 0 means that we received non number value
        if ((line_int = strtol(line, NULL, 10)))
        {
            // Negative value, taht is not -1 means error
            if (line_int < -1)
                continue;

            request.iters = line_int;
            request.code = ((line_int == -1) ? (EXIT) : (OK));
            break;
        }

        printf("\n");
    }

    return request;
}

// Make an actioon according to the rrequest made. Also return the reply from the server
reply_t * process_request(request_t request, CLIENT * clnt)
{
    reply_t * reply;

    if (request.code == EXIT)
    {
        puts("Closing client...");
        exit(EXIT_SUCCESS);
    }
    else if (request.code == OK)
    {
        puts("Calling the calculation function...");
        reply = calc_pi_1(&request, clnt);
        
        // This means that an error with the 
        if (reply == NULL)
        {
            puts("Failure in pi calculation");

            reply = (reply_t *) malloc(1 * sizeof(reply_t));
            reply->code = ERROR;
            
            return reply;
        }

        return reply;
    }

    return NULL;
}

// Function to process the reply from the server
void process_reply(reply_t * reply)
{
    if (reply == NULL)
        puts("Failed to calculate the pi. Restarting...");
    else if (reply->code == ERROR)
        puts("Error occurred durring calculation");
    else if (reply->code == OK)
        printf("Calculated pi: %.16f\n", reply->pi);
}

void
calc_pi_client (char *host)
{
	CLIENT * clnt;
	reply_t * reply;
	request_t request;

#ifndef	DEBUG
	clnt = clnt_create (host, PI_CALC, PI_CALC_V_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

    /* Main implementation */
    while (1)
    {
        // Get message and return the request type
        request = get_input();
        // Now check the input for next action
        reply = process_request(request, clnt);
        // And print the result if the user did not choose to exit
        process_reply(reply);
    }
    
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	
    host = argv[1];
	calc_pi_client (host);

    return EXIT_SUCCESS;
}
