/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_PI_H_RPCGEN
#define _CALC_PI_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct request_t {
	int code;
	int iters;
};
typedef struct request_t request_t;

struct reply_t {
	int code;
	double pi;
};
typedef struct reply_t reply_t;

#define PI_CALC 0x13371337
#define PI_CALC_V_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define calc_pi 1
extern  reply_t * calc_pi_1(request_t *, CLIENT *);
extern  reply_t * calc_pi_1_svc(request_t *, struct svc_req *);
extern int pi_calc_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define calc_pi 1
extern  reply_t * calc_pi_1();
extern  reply_t * calc_pi_1_svc();
extern int pi_calc_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_request_t (XDR *, request_t*);
extern  bool_t xdr_reply_t (XDR *, reply_t*);

#else /* K&R C */
extern bool_t xdr_request_t ();
extern bool_t xdr_reply_t ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_PI_H_RPCGEN */
