/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_PI_H_RPCGEN
#define _CALC_PI_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef int groupid_t;

struct worker_args_t {
	int rank;
	int thread_iters;
	int iters_max;
};
typedef struct worker_args_t worker_args_t;

struct master_args_t {
	groupid_t groupid;
	int thread_num;
	double sum;
};
typedef struct master_args_t master_args_t;

#define MAS_WOR 0x123456
#define MAS_WOR_V_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define get_groupid 1
extern  groupid_t * get_groupid_1(void *, CLIENT *);
extern  groupid_t * get_groupid_1_svc(void *, struct svc_req *);
#define assign_to_task 2
extern  worker_args_t * assign_to_task_1(master_args_t *, CLIENT *);
extern  worker_args_t * assign_to_task_1_svc(master_args_t *, struct svc_req *);
#define send_sum 3
extern  int * send_sum_1(master_args_t *, CLIENT *);
extern  int * send_sum_1_svc(master_args_t *, struct svc_req *);
#define mark_as_finished 4
extern  int * mark_as_finished_1(groupid_t *, CLIENT *);
extern  int * mark_as_finished_1_svc(groupid_t *, struct svc_req *);
extern int mas_wor_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define get_groupid 1
extern  groupid_t * get_groupid_1();
extern  groupid_t * get_groupid_1_svc();
#define assign_to_task 2
extern  worker_args_t * assign_to_task_1();
extern  worker_args_t * assign_to_task_1_svc();
#define send_sum 3
extern  int * send_sum_1();
extern  int * send_sum_1_svc();
#define mark_as_finished 4
extern  int * mark_as_finished_1();
extern  int * mark_as_finished_1_svc();
extern int mas_wor_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_groupid_t (XDR *, groupid_t*);
extern  bool_t xdr_worker_args_t (XDR *, worker_args_t*);
extern  bool_t xdr_master_args_t (XDR *, master_args_t*);

#else /* K&R C */
extern bool_t xdr_groupid_t ();
extern bool_t xdr_worker_args_t ();
extern bool_t xdr_master_args_t ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_PI_H_RPCGEN */
