/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calc_pi.h"

bool_t
xdr_groupid_t (XDR *xdrs, groupid_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_worker_args_t (XDR *xdrs, worker_args_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->rank))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->thread_iters))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->iters_max))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_master_args_t (XDR *xdrs, master_args_t *objp)
{
	register int32_t *buf;

	 if (!xdr_groupid_t (xdrs, &objp->groupid))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->thread_num))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->sum))
		 return FALSE;
	return TRUE;
}
