/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "calculator.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

reply_t *
add_1(request_t *argp, CLIENT *clnt)
{
	static reply_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, add,
		(xdrproc_t) xdr_request_t, (caddr_t) argp,
		(xdrproc_t) xdr_reply_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

reply_t *
deduct_1(request_t *argp, CLIENT *clnt)
{
	static reply_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, deduct,
		(xdrproc_t) xdr_request_t, (caddr_t) argp,
		(xdrproc_t) xdr_reply_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

reply_t *
divide_1(request_t *argp, CLIENT *clnt)
{
	static reply_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, divide,
		(xdrproc_t) xdr_request_t, (caddr_t) argp,
		(xdrproc_t) xdr_reply_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

reply_t *
multiply_1(request_t *argp, CLIENT *clnt)
{
	static reply_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, multiply,
		(xdrproc_t) xdr_request_t, (caddr_t) argp,
		(xdrproc_t) xdr_reply_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
