/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

/* Just modified a little bit these functions. Just added the implementation */

/*
 * The big changes go here. The server here acts as a header file of some kind, opened
 * in a socket. Only the remote procedures are contained here and their base
 * implementations. No socket initialization is needed from the developer's part.
*/

#include "calculator.h"

// Error codes
#define OK 0
#define ERROR 1

reply_t *
add_1_svc(request_t * info, struct svc_req *rqstp)
{
	static reply_t  reply;

    reply.result = info->val1 + info->val2;
    reply.code = OK;

	return &reply;
}

reply_t *
deduct_1_svc(request_t * info, struct svc_req *rqstp)
{
	static reply_t  reply;

    reply.result = info->val1 - info->val2;
    reply.code = OK;

	return &reply;
}

reply_t *
divide_1_svc(request_t * info, struct svc_req *rqstp)
{
	static reply_t  reply;

    if (info->val2 == 0)
    {
        reply.result = 0; // A dummy value actually
        reply.code = ERROR;
        return &reply;
    }

    reply.result = info->val1 / info->val2;
    reply.code = OK;

	return &reply;
}

reply_t *
multiply_1_svc(request_t * info, struct svc_req *rqstp)
{
	static reply_t reply;

    reply.result = info->val1 * info->val2;
    reply.code = OK;

	return &reply;
}
